services:
  mysql:
    image: mysql:8.4.8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "janina"
      MYSQL_DATABASE: appdb
      MYSQL_USER: janina
      MYSQL_PASSWORD: "janina"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -pjanina --silent"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  cloudbeaver:
    image: dbeaver/cloudbeaver:26.0.2
    restart: unless-stopped
    environment:
      CB_SERVER_NAME: "Local DB Admin"
      CB_SERVER_URL: "http://localhost:8978/"
      CB_ADMIN_NAME: janina
      CB_ADMIN_PASSWORD: "janina"
    ports:
      - "8978:8978"
    volumes:
      - cloudbeaver_data:/opt/cloudbeaver/workspace

volumes:
  mysql_data:
  cloudbeaver_data:
